---
title: Johnson Portfolio
logo: /assets/img/headshot_circle.png
theme: jekyll-theme-minimal
---

# Welcome to My Portfolio

Hello! I'm **Johnson Kinuthia Gitau**, a passionate Data Analyst specializing in finance analytics and market trend analysis.
