---
title: Johnson Portfolio
logo: /GITHUB PROFILE1.jpg
theme: jekyll-theme-minimal
---

# Welcome to My Portfolio

Hello! I'm **Johnson Kinuthia Gitau**, a passionate Data Analyst specializing in finance analytics and market trend analysis.
